version = 1

[merge]
automerge_label = "ğŸš¢ ship it ğŸ¤–"
priority_merge_label = "ğŸ˜µ priority merge ğŸ¤–"

[merge.automerge_dependencies]
# auto merge all PRs opened by "dependabot" that are "minor" or "patch" version upgrades. "major" version upgrades will be ignored.
versions = ["minor", "patch"]
usernames = ["dependabot", "renovate"]

[update]
ignored_usernames = ["dependabot", "renovate"]
